### ISSUE TITLE
Why no data augmentation used for training ELEVATER?

### ISSUE THREAD

**Issue by BrandonHanx** [sIncerass/MVLPT#2]
Hi, @sIncerass @bronyayang 

I noticed that the transforms used for train and test are the same for ELEVATER, which means there is no data augmentation used during training.
But for COOP data, "random_resized_crop" and "random_flip" are used.
I guess data augmentation could be important for few-shot learning. Do you have any reasons for not using?

https://github.com/sIncerass/MVLPT/blob/7b246b8afd29d299c9c4f7889aae025c10f77d29/trainers/vision_benchmark/evaluation/feature.py#L539-L553

**Comment by bronyayang** [comment]
Hi,

ELEVATER is a few shot benchmark, and we use this vision_benchmark folder they provided us in their [repo](https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC]). We agree with you that data augmentation could be important for few-shot learning. However, for fair comparison with the benchmark [baselines](https://eval.ai/web/challenges/challenge-page/1832/leaderboard/4303), we did not add additional augmentation. :)
